name: Pre-Commit
on: [push]
jobs:
  Setup-Env:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
  Pre-Commit-Checks:
    runs-on: ubuntu-latest
    needs: Setup-Env
    steps:
      - run: echo "ğŸ§ running pre-commit tests on a ${{ runner.os }} server hosted by GitHub!"
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.3
  Slack-Notification:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#code-review'
          message: Starting Docker Build and Push...
      if: always()

