name: Pre-Commit
on: [push]
jobs:
  Setup-Env:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
  Pre-Commit-Checks:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
  Slack-Notification:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
    env:
      REPOSITORY_URL: docker.pkg.github.com
      IMAGE_NAME: ${{ github.repository }}/alerta-cli
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: act10ns/slack@v1
        with:
          status: starting
          channel: '#code-review'
          message: Starting Docker Build and Push...
        if: always()